/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    Card: typeof import('./src/components/ui/card/Card.vue')['default']
    CardContent: typeof import('./src/components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./src/components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./src/components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./src/components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./src/components/ui/card/CardTitle.vue')['default']
    ExerciseFooter: typeof import('./src/components/exercise/ExerciseFooter.vue')['default']
    ExerciseOptions: typeof import('./src/components/exercise/ExerciseOptions.vue')['default']
    ExerciseSkeleton: typeof import('./src/components/exercise/ExerciseSkeleton.vue')['default']
    ExerciseSummary: typeof import('./src/components/exercise/ExerciseSummary.vue')['default']
    ExerciseTypeIn: typeof import('./src/components/exercise/ExerciseTypeIn.vue')['default']
    Progress: typeof import('./src/components/ui/progress/Progress.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('./src/components/ui/skeleton/Skeleton.vue')['default']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    Toast: typeof import('./src/components/ui/toast/Toast.vue')['default']
    ToastAction: typeof import('./src/components/ui/toast/ToastAction.vue')['default']
    ToastClose: typeof import('./src/components/ui/toast/ToastClose.vue')['default']
    ToastDescription: typeof import('./src/components/ui/toast/ToastDescription.vue')['default']
    Toaster: typeof import('./src/components/ui/toast/Toaster.vue')['default']
    ToastProvider: typeof import('./src/components/ui/toast/ToastProvider.vue')['default']
    ToastTitle: typeof import('./src/components/ui/toast/ToastTitle.vue')['default']
    ToastViewport: typeof import('./src/components/ui/toast/ToastViewport.vue')['default']
    Tooltip: typeof import('./src/components/ui/tooltip/Tooltip.vue')['default']
    TooltipContent: typeof import('./src/components/ui/tooltip/TooltipContent.vue')['default']
    TooltipProvider: typeof import('./src/components/ui/tooltip/TooltipProvider.vue')['default']
    TooltipTrigger: typeof import('./src/components/ui/tooltip/TooltipTrigger.vue')['default']
  }
}
